kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  proxy-connect-timeout: "10s"
  proxy-read-timeout: "10s"
  client-max-body-size: "2m"
  http-snippet: |
    limit_req_zone $binary_remote_addr zone=one_zone:10m rate=1r/m;